repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: This hook removes trailing whitespace.
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format


  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages: [commit-msg]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        name: MyPy
        description: This hook runs MyPy to check Python type hints.
        # args: ["--explicit-package-bases"]
