apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pve-prod-password-generator-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabszs/FastApi--Password-Generator.git
    path: k8s
    targetRevision: gitops
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
